name: nea_prototype_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
## the following lines of code state the dependenices of my code, different dependencies allow me to use different packages
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0 # Resizes text to restrict it to a specific number of lines
  cached_network_image: ^2.0.0 # Library which shows images from the Internet and keeps them in cache
  cloud_firestore: ^0.13.3 # Flutter plugin to use the Cloud Firestore API
  firebase_auth: ^0.15.2 # Flutter plugin to use the Firebase Authentication API
  provider: ^3.2.0 # Wraps around InheritedWidget to make them easier to use
  shared_preferences: ^0.5.6+3 # Used to save a collection of key-value pairs
  random_string: ^2.0.1 # Libarry for generating random ascii strings
  persistent_bottom_nav_bar: ^4.0.2 # Static/persistent bottom navigation bar for Flutter
  custom_navigator: ^0.3.0 # Allows create of own navigator 
  toggle_switch: ^1.4.0  # Allows use of the toggle swicth
  walkthrough: ^0.0.3 # Allows use of the walkthrough packag

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true # allows use of the material icons class

# To add assets to your application, add an assets section, like this:
  assets: # defines the location of the assets folder
   - lib/assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
